# Generated by Django 4.1.1 on 2022-10-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_productattribute_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
